{
 "title": "Polymesh Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node count by Polymesh version",
   "type": "bargauge",
   "description": "Shows how many nodes are running what version of Polymesh",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (version) (polymesh_build_info)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Node roles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(polymesh_node_roles == 4)",
     "legendFormat": "operator"
    },
    {
     "expr": "count(polymesh_node_roles == 3)",
     "legendFormat": "sentry"
    },
    {
     "expr": "count(polymesh_node_roles == 1)",
     "legendFormat": "general"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import queue justifications submitted rate [1m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_import_queue_justifications_submitted[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Blocks in import queue",
     "type": "graph",
     "description": "A healthy node should be able to process blocks soon after they are added to the import queue.  A node that has a growing number of blocks in the import queue is a node that is going to be lagging on the network. ",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "polymesh_sync_queued_blocks", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "Minimum number of justifications pending [1m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(polymesh_sync_extra_justifications[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Transactions in ready queue",
     "type": "graph",
     "description": "A healthy node should be able to process transactions soon after they are added to the ready queue.  A node that has a growing number of transactions in the ready queue is a node that is going to be lagging on the network.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "polymesh_ready_transactions_number",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target block",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar value for the target block.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "polymesh_block_height{status=\"sync_target\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Target block increase [1m]",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar rate of block increase.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(polymesh_block_height{status=\"sync_target\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Finalized block",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar value for the finalised block.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "polymesh_block_height{status=\"finalized\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Finalized block increase [1m]",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar rate of block increase.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(polymesh_block_height{status=\"finalized\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Best block",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar value for the best block.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "polymesh_block_height{status=\"best\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Best block increase [1m]",
     "type": "graph",
     "description": "All monitored Polymesh nodes should have a similar rate of block increase.  A noticeable deviation is an indicator of the node having troubles or (in the case of new nodes) not being ready for operation.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(polymesh_block_height{status=\"best\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Node is syncing the chain",
     "type": "graph",
     "description": "A new node that is not up to date with the chain will be syncing its blocks.  While a node is syncing it will not be performing its assigned function.  A healthy, up to date node will not be syncing the chain.  ",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "polymesh_sub_libp2p_is_major_syncing",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Best block time [2m]",
     "type": "graph",
     "description": "A healthy Polymesh chain should produce a block every six seconds on average.  Significant deviations from that number are an indicator of problems on the network.  The causes could be various - underspecced nodes, clock skew, DDoS, etc. ",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "120 / max(increase(polymesh_block_height{status=\"best\"}[2m]))",
       "legendFormat": "Min"
      },
      {
       "expr": "120 / median(increase(polymesh_block_height{status=\"best\"}[2m]))",
       "legendFormat": "Avg"
      },
      {
       "expr": "120 / min(increase(polymesh_block_height{status=\"best\"}[2m]))",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming connection handshake - Limit reached",
     "type": "graph",
     "description": "Rate of rejected incoming connections due to the connection limit having been reached",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_incoming_connections_handshake_errors_total{reason=\"limit-reached\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Pending connections - Limit reached",
     "type": "graph",
     "description": "Rate of rejected outgoing connections due to the connection limit having been reached",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_pending_connections_errors_total{reason=\"limit-reached\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Incoming connection handshake - Invalid peerID",
     "type": "graph",
     "description": "Rate of rejected incoming connections due to the peer having an invalid peerID",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_incoming_connections_handshake_errors_total{reason=\"invalid-peer-id\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Pending connection - Invalid PeerID",
     "type": "graph",
     "description": "Rate of rejected outgoing connections due to the peer having an invalid peerID",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_pending_connections_errors_total{reason=\"invalid-peer-id\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Incoming connection handshake - transport error",
     "type": "graph",
     "description": "Rate of rejected incoming connections due to transport errors",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_incoming_connections_handshake_errors_total{reason=\"transport-error\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Pending connection - transport error",
     "type": "graph",
     "description": "Rate of rejected outgoing connections due to transport errors",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_pending_connections_errors_total{reason=\"transport-error\"}[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Peer connections rate [1m]",
     "type": "graph",
     "description": "A healthy edge node on the Polymesh network should  have a stable set of peers.  Churn on the peer connection rate should be unexpected, and may be an indicator of various network issues. ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(polymesh_sub_libp2p_connections_opened_total{direction=\"in\"}[1m])",
       "legendFormat": "In: {{ host }}"
      },
      {
       "expr": "rate(polymesh_sub_libp2p_connections_opened_total{direction=\"out\"}[1m]) * -1",
       "legendFormat": "Out: {{ host }}"
      }
     ]
    },
    {
     "title": "Max peers [1m]",
     "type": "graph",
     "description": "If an operator node has zero peers then this needs to be addressed ASAP - an unconnected operator cannot produce blocks and will be slashed.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(polymesh_sync_peers[1m])",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  }
 ]
}